ccflags-y += -Idrivers/media/platform/msm/lenovo/camera/camera-driver/
ccflags-y += -Idrivers/media/platform/msm/lenovo/camera/camera-driver/sensor
ccflags-y += -Idrivers/media/platform/msm/lenovo/camera/camera-driver/sensor/cci
obj-$(CONFIG_LENOVOB_CAMERA)   += msm_camera_io_util.o msm_camera_cci_i2c.o msm_camera_qup_i2c.o msm_camera_spi.o msm_camera_dt_util.o
