

obj-y += lenovo_lcd_effect.o lenovo_lcd_effect_color.o lenovo_lcd_effect_mode.o lenovo_fb.o
obj-y += passion/

#obj-y += lenovo_lcd_effect_project.o

#obj-y += lenovo_lcd_effect.o lenovo_lcd_effect_mode.o lenovo_lcd_effect_color.o lenovo_fb.o




