#gt915 touchpanel driver


obj-$(CONFIG_GT1151_TOUCHPANEL_DRIVER)	+= gt1x.o gt1x_extents.o gt1x_generic.o
#gt915 update file
obj-$(CONFIG_GT1151_TOUCHPANEL_UPDATE)	+= gt1x_update.o
#debug tool
obj-$(CONFIG_GT1151_TOUCHPANEL_DEBUG)	+= gt1x_tools.o
