ccflags-y += -Idrivers/media/platform/msm/lenovo/camera/camera-driver
ccflags-y += -Idrivers/media/platform/msm/lenovo/camera/camera-driver/sensor/io
obj-$(CONFIG_LENOVOB_CAMERA) += msm_isp.o msm_buf_mgr.o msm_isp_util.o msm_isp_axi_util.o msm_isp_stats_util.o
obj-$(CONFIG_LENOVOB_CAMERA) += msm_isp47.o msm_isp46.o msm_isp44.o msm_isp40.o msm_isp32.o
